version: '3.8'

services:
  db:
    image: postgres:16
    container_name: itsupp_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - itsupp_postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: itsupp_app
    restart: always
    depends_on:
      - db
    ports:
      - "8443:8443"
    env_file:
      - .env

volumes:
  itsupp_postgres_data: